version: '3'

services:
    db:
        image: mysql:5.7.18
        #image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
            #- db_conf:/etc/mysql/conf.d
        environment:
            MYSQL_ROOT_PASSWORD: my_secret
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
        healthcheck:
            test: "mysqladmin --user=$MYSQL_USER --password=$MYSQL_PASSWORD ping"
            interval: 10s
            timeout: 2s
            retries: 2
        deploy:
            restart_policy:
                max_attempts: 2

    wordpress:
        image: wordpress:4-php7.0
        #image: wordpress:4-php7.1
        volumes:
            - wp_data:/var/www/html
        depends_on:
            - db
        ports:
            - "8080:80"
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress
        healthcheck:
            test: "curl -f http://localhost"
            interval: 10s
            timeout: 2s
            retries: 2
        deploy:
            restart_policy:
                max_attempts: 2

volumes:
    db_data:
    db_conf:
    wp_data:
