version: '3'

services:
    db:
        # image has built-in healthcheck
        image: healthcheck/mariadb
        volumes:
            - db_data2:/var/lib/mysql
        command:  ["mysqld", "--extra-port=3366"]
        environment:
            MYSQL_ROOT_PASSWORD: my_secret
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
        deploy:
            placement:
                constraints: [node.role == manager]

    wordpress:
        image: wordpress:4.8.0-php7.0  # 4.8.0-php7.0 or 4.8.0-php7.1
        volumes:
            - wp_data2:/var/www/html
        depends_on:
            - db
        ports:
            - "8081:80"
        environment:
            WORDPRESS_DB_HOST: db:3366
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost"]
            interval: 15s
            timeout: 3s
            retries: 3

volumes:
    db_data2:
    wp_data2:
